### ISSUE TITLE
Class 'Symfony\Component\DependencyInjection\Loader\YamlFileLoader' not found

### ISSUE THREAD

**Issue by Gummibeer** [sauls/options-resolver#2]
> **Exception**
> Class `Symfony\Component\DependencyInjection\Loader\YamlFileLoader` not found

I tried to require this package but it looks like it doesn't work without a whole symfony setup running. 😕

**Comment by sauls** [comment]
No you don't full symfony framework dependency , the library itself depends on https://github.com/sauls/helpers and there in composer.json under require section it lacks the symfony/yaml entry (my bad :-1: . I have in mind to revisit and improve the libraries someday ....
